title: "Technische Hochschule Rosenheim"
domain: "http://th-rosenheim.de"
email: marcel.tilly@th-rosenheim.de
description: "Vorlesung zum fachwissenschaftlichen Modul Internet of Things"
baseurl: ""
url: "https://hsro-inf-iot.github.io"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["matworx"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
